name: e2e-tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
        with:
          ref: feature/version_2
      - name: Install dependecies
        run: npm i
      - name: Test application
        run: npm run test:e2e
